version: "3.9"

services:
  api:
    build:
      context: /media/sf_jayson-todo-list-app/backend
      dockerfile: docker/Dockerfile
    container_name: todo-api
    volumes:
      - /media/sf_jayson-todo-list-app/backend:/var/www
    depends_on:
      - mysql
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=todo_db
      - DB_USERNAME=todo_user
      - DB_PASSWORD=secret
    command: php-fpm
    networks:
      - todo-network

  nginx:
    image: nginx:alpine
    container_name: todo-nginx
    ports:
      - "8000:80"
    volumes:
      - /root/jayson-todo-list-app/api:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
    networks:
      - todo-network

  mysql:
    image: mysql:8.0
    container_name: todo-mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootsecret
      MYSQL_DATABASE: todo_db
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - todo-network

  portainer:
    image: portainer/portainer-ce
    container_name: todo-portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - todo-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: todo-phpmyadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: rootsecret
    depends_on:
      - mysql
    networks:
      - todo-network

  soketi:
    image: "quay.io/soketi/soketi:latest-16-alpine"
    container_name: todo-soketi
    environment:
      SOKETI_DEBUG: "1"
      SOKETI_METRICS_SERVER_PORT: "9601"
      SOKETI_APP_ID: app-id
      SOKETI_APP_KEY: app-key
      SOKETI_APP_SECRET: app-secret
    ports:
      - "6001:6001"
      - "9601:9601"
    networks:
      - todo-network

volumes:
  mysql_data:
  portainer_data:

networks:
  todo-network:
    driver: bridge
